### ISSUE TITLE
After reinstalling packages conn refused

### ISSUE THREAD

**Issue by sarensabertooth** [directus/gatsby-source-directus#23] opened 2023-04-07 08:16 UTC
It all worked before, but I had to reinstall packages, and now I am lost somewhere in either dependency hell, though that shouldn't be it, and authentication failed.
The token 100% works, I changed it 3 times now in Directus to make sure there's no weird caching happening. 
Tried deleting cache folder etc etc. Nothing works.

<img width="579" alt="Screen Shot 2023-04-07 at 10 04 55" src="https://user-images.githubusercontent.com/9402883/230571025-e1bd867a-b55b-4b3a-87a6-0c953ed67751.png">

These are my deps:
` "@directus/gatsby-source-directus": "^9.15.1",
    "@hookform/error-message": "^2.0.1",
    "@mdx-js/react": "^2.3.0",
    "@react-icons/all-files": "^4.1.0",
    "gatsby": "^5.7.0",
    "gatsby-cookie-notice": "^1.0.6",
    "gatsby-plugin-gdpr-cookies": "^2.0.9",
    "gatsby-plugin-google-gtag": "^5.7.0",
    "gatsby-plugin-image": "^3.7.0",
    "gatsby-plugin-manifest": "^5.7.0",
    "gatsby-plugin-mdx": "^5.7.0",
    "gatsby-plugin-offline": "^6.8.0",
    "gatsby-plugin-robots-txt": "^1.8.0",
    "gatsby-plugin-sass": "^6.7.0",
    "gatsby-plugin-sharp": "^5.7.0",
    "gatsby-plugin-sitemap": "^6.7.0",
    "gatsby-source-filesystem": "^5.7.0",
    "gatsby-source-graphql": "^5.8.0",
    "gatsby-transformer-sharp": "^5.7.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-hook-form": "^7.43.5",
    "react-hook-form-persist": "^3.0.0",
    "sass": "^1.59.2"`

**Comment by rijkvanzanten** [comment] 2023-04-07 18:01
ECONNREFUSED on localhost:8055. Is Directus running on the same host on port 8055?

**Comment by sarensabertooth** [comment] 2023-04-07 19:14
> ECONNREFUSED on localhost:8055. Is Directus running on the same host on port 8055?

Yes, I’m not sure how to check if all the APIs are accessible, but I can login under localhost:8055/admin
It’s super frustrating as it worked previously. And I am having a hard time Troubleshooting this at all. Don’t know where to begin.

**Comment by ghost** [comment] 2023-04-19 09:55
> > ECONNREFUSED on localhost:8055. Is Directus running on the same host on port 8055?
> 
> Yes, I’m not sure how to check if all the APIs are accessible, but I can login under localhost:8055/admin It’s super frustrating as it worked previously. And I am having a hard time Troubleshooting this at all. Don’t know where to begin.

Hey :) i had the same error and i fixed it by swapping the `options.url` value from `http://localhost:8055/api` to `http://0.0.0.0:8055/api` <3

**Comment by azrikahar** [comment] 2023-04-19 10:10
@ahu-cap3 thanks for sharing! That actually does sounds like https://github.com/directus/gatsby-source-directus/issues/12#issuecomment-1317372720, which should technically be Nodejs (17 and up) related. 

@sarensabertooth did you update your Node version by any chance? I've only now notice that your first screenshot shows `::1:8055`, which should be the same "root cause" of said Node update which resolves ipv6 first by default. Does changing `localhost` to `127.0.0.1` work for you?

The current information leads me to believe it should be Node related instead of this gatsby-source-directus package so I'll close this for now, but we'll re-open this issue if it's actually a different issue 👍

**Closed as not planned by azrikahar** 2023-04-19 10:10 UTC
